# Autogenerated file. ANY CHANGES WILL BE OVERWRITTEN
from to_python.core.types import FunctionType, \
    FunctionArgument, \
    FunctionArgumentValues, \
    FunctionReturnTypes, \
    FunctionSignature, \
    FunctionDoc, \
    FunctionData, \
    CompoundFunctionData
     
DUMP_PARTIAL = [
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textCreateDisplay',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['textdisplay'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='A textdisplay|text display is like a canvas that can contain many textitem|items of text. Each display can be seen by multiple observers (players) and each player can see multiple displays.' ,
                arguments={
                    
                },
                result='' ,
            ),
            url='textCreateDisplay',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textCreateTextItem',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='text',
                                argument_type=FunctionType(
                                    names=['string'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='x',
                                argument_type=FunctionType(
                                    names=['float'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='y',
                                argument_type=FunctionType(
                                    names=['float'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='priority',
                                argument_type=FunctionType(
                                    names=['string'],
                                    is_optional=True,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='red',
                                argument_type=FunctionType(
                                    names=['int'],
                                    is_optional=True,
                                ),
                                default_value='255',
                            )
                        ],
                        [
                            FunctionArgument(
                                name='green',
                                argument_type=FunctionType(
                                    names=['int'],
                                    is_optional=True,
                                ),
                                default_value='255',
                            )
                        ],
                        [
                            FunctionArgument(
                                name='blue',
                                argument_type=FunctionType(
                                    names=['int'],
                                    is_optional=True,
                                ),
                                default_value='255',
                            )
                        ],
                        [
                            FunctionArgument(
                                name='alpha',
                                argument_type=FunctionType(
                                    names=['int'],
                                    is_optional=True,
                                ),
                                default_value='255',
                            )
                        ],
                        [
                            FunctionArgument(
                                name='scale',
                                argument_type=FunctionType(
                                    names=['float'],
                                    is_optional=True,
                                ),
                                default_value='1',
                            )
                        ],
                        [
                            FunctionArgument(
                                name='alignX',
                                argument_type=FunctionType(
                                    names=['string'],
                                    is_optional=True,
                                ),
                                default_value='"left"',
                            )
                        ],
                        [
                            FunctionArgument(
                                name='alignY',
                                argument_type=FunctionType(
                                    names=['string'],
                                    is_optional=True,
                                ),
                                default_value='"top"',
                            )
                        ],
                        [
                            FunctionArgument(
                                name='shadowAlpha',
                                argument_type=FunctionType(
                                    names=['int'],
                                    is_optional=True,
                                ),
                                default_value='0',
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function creates a text item. A text item represents a single area of text, much like a label does in standard GUI programming. A text item can only be seen by players if it is added to a textdisplay using textDisplayAddText. Each text item can be added to multiple displays, if need be.' ,
                arguments={
                    "text": """: A string of text you want to display """,
                    "x": """: A floating point number between 0.0 and 1.0 indicating how far across the screen the text should be shown, as a percentage of the width, from the left hand side. """,
                    "y": """: A floating point number between 0.0 and 1.0 indicating how far down the screen the text should be shown, as a percentage of the height, from the top. """,
                    "priority": """: How important it is that this text should be up to date on clients screens. Valid values are: low, medium, high which are aliases for 0, 1 and 2 respectively. """,
                    "red": """: A value between 0 and 255 indicating how red the text should be. """,
                    "green": """: A value between 0 and 255 indicating how green the text should be. """,
                    "blue": """: A value between 0 and 255 indicating how blue the text should be. """,
                    "alpha": """: A value between 0 and 255 indicating how transparent the text should be, with 0 being fully transparent, and 255 being opaque. """,
                    "scale": """: A floating point value indicating the scale of the text. The default is 1.0, which is around 12pt. """,
                    "alignX": """: A string representing the X-alignment of the text. (left, center, right) """,
                    "alignY": """: A string representing the Y-alignment of the text. (top, center, bottom) """,
                    "shadowAlpha": """: A value between 0 and 255 indicating how dark the drop shadow should be. """
                },
                result='returns a textitem object.' ,
            ),
            url='textCreateTextItem',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textDestroyDisplay',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['bool'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='display',
                                argument_type=FunctionType(
                                    names=['textdisplay'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function destroys a text display and will unlink all the textitems on it. This does not stop the textitems existing, but anyone who was observing the textitems through this display will stop seeing them.' ,
                arguments={
                    "display": """This is the textdisplay that you wish to have destroyed. """
                },
                result='' ,
            ),
            url='textDestroyDisplay',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textDestroyTextItem',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['void'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextitem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function destroys a textitem object.' ,
                arguments={
                    "theTextitem": """The text item you wish to destroy. """
                },
                result='' ,
            ),
            url='textDestroyTextItem',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textDisplayAddObserver',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['void'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='display',
                                argument_type=FunctionType(
                                    names=['textdisplay'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='playerToAdd',
                                argument_type=FunctionType(
                                    names=['player'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function adds a player as an observer of a textdisplay. This allows the player to see any textitems that the textdisplay contains.' ,
                arguments={
                    "display": """: The textdisplay to add the player to as an observer. """,
                    "playerToAdd": """: The player that should observe the textdisplay. """
                },
                result='' ,
            ),
            url='textDisplayAddObserver',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textDisplayAddText',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['void'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='displayToAddTo',
                                argument_type=FunctionType(
                                    names=['textdisplay'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='itemToAdd',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function adds a textitem to a textdisplay. This allows any observers of the textdisplay to see the textitem.' ,
                arguments={
                    "displayToAddTo": """: The textdisplay to add the textitem to. """,
                    "itemToAdd": """: The textitem to add to the display. """
                },
                result='' ,
            ),
            url='textDisplayAddText',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textDisplayGetObservers',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['table'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theDisplay',
                                argument_type=FunctionType(
                                    names=['textdisplay'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function can be used to retrieve all the players  currently observing a specified textdisplay.' ,
                arguments={
                    "theDisplay": """: The textdisplay of which observers you want to get. """
                },
                result='returns a table of players that are observers of the display or false if invalid textdisplay is passed.' ,
            ),
            url='textDisplayGetObservers',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textDisplayIsObserver',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['bool'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='display',
                                argument_type=FunctionType(
                                    names=['textdisplay'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='thePlayer',
                                argument_type=FunctionType(
                                    names=['player'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function checks if a player can see the specified textdisplay.' ,
                arguments={
                    "display": """: The textdisplay. """,
                    "thePlayer": """: The player. """
                },
                result='return true if textdisplay is showing, or false if not.' ,
            ),
            url='textDisplayIsObserver',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textDisplayRemoveObserver',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['bool'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='display',
                                argument_type=FunctionType(
                                    names=['textdisplay'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='playerToRemove',
                                argument_type=FunctionType(
                                    names=['player'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function removes a player observer of a textdisplay. This stops the player from being able to see textitems that the textdisplay contains.' ,
                arguments={
                    "display": """: The textdisplay to remove the player from as an observer. """,
                    "playerToRemove": """: The player that should be removed from the textdisplay. """
                },
                result='' ,
            ),
            url='textDisplayRemoveObserver',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textDisplayRemoveText',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['void'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='displayToRemoveFrom',
                                argument_type=FunctionType(
                                    names=['textdisplay'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='itemToRemove',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function removes a textitem from a textdisplay. This stops any observers of the textdisplay from being able to see the textitem.' ,
                arguments={
                    "displayToRemoveFrom": """: The textdisplay to remove the textitem from. """,
                    "itemToRemove": """: The textitem to remove from the display. """
                },
                result='' ,
            ),
            url='textDisplayRemoveText',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemGetColor',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['int'],
                                    is_optional=False,
                                ),
                    FunctionType(
                                    names=['int'],
                                    is_optional=False,
                                ),
                    FunctionType(
                                    names=['int'],
                                    is_optional=False,
                                ),
                    FunctionType(
                                    names=['int'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextItem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function allows you to retrieve the color of a text item.' ,
                arguments={
                    "theTextItem": """The text item you wish to retrieve the color of. """
                },
                result='returns four integers in rgba format, with a maximum value of 255 for each. the values are, in order, red, green, blue, and alpha. alpha decides transparency where 255 is opaque and 0 is transparent. false is returned if the text item is invalid.' ,
            ),
            url='textItemGetColor',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemGetPosition',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['float'],
                                    is_optional=False,
                                ),
                    FunctionType(
                                    names=['float'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextItem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function allows retrieval of the position of a text item.' ,
                arguments={
                    "theTextItem": """The textitem you wish to retrieve the position of """
                },
                result='returns two floats of the x and y position on the screen, where the maximum value is 1.0.' ,
            ),
            url='textItemGetPosition',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemGetPriority',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['int'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='textitemToCheck',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function retrieves the priority of a text item.  Priority defines the rate at whihc a text item is updated' ,
                arguments={
                    "textitemToCheck": """The text item you wish to retrieve the priority of. """
                },
                result='returns a integer of the priority of a text item, 0 = low, 1 = medium, 2 = high.' ,
            ),
            url='textItemGetPriority',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemGetScale',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['float'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextitem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function allows retrieval of the scale or size of a text item.' ,
                arguments={
                    "theTextitem": """The text item you wish to retrieve the scale of """
                },
                result='returns a floating point of the scale of the text. 1.0 is around 12pt.' ,
            ),
            url='textItemGetScale',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemGetText',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['string'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextitem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function returns the current text of the specified textitem.' ,
                arguments={
                    "theTextitem": """A valid textitem. """
                },
                result='returns a string containing the text if the function was successful, false otherwise.' ,
            ),
            url='textItemGetText',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemSetColor',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['bool'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextItem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='r',
                                argument_type=FunctionType(
                                    names=['int'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='g',
                                argument_type=FunctionType(
                                    names=['int'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='b',
                                argument_type=FunctionType(
                                    names=['int'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='a',
                                argument_type=FunctionType(
                                    names=['int'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function sets the color of a text item.' ,
                arguments={
                    "theTextItem": """The textitem you wish to set the color of. """,
                    "red": """The amount of red in the text items color (0 - 255). """,
                    "green": """The amount of green in the text items color (0 - 255). """,
                    "blue": """The amount of blue in the text items color (0 - 255). """,
                    "alpha": """The amount of alpha in the text items color (0 - 255). Alpha decides transparency where 255 is opaque and 0 is transparent. """
                },
                result='returns true if the color was successfully set, false otherwise.' ,
            ),
            url='textItemSetColor',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemSetPosition',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['bool'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextItem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='x',
                                argument_type=FunctionType(
                                    names=['float'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='y',
                                argument_type=FunctionType(
                                    names=['float'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function allows the setting of the position of a text item.' ,
                arguments={
                    "theTextItem": """The text item that you want to move """,
                    "x": """A floating point number between 0.0 and 1.0 indicating how far across the screen the text should be shown, as a percentage of the width, from the left hand side. """,
                    "y": """A floating point number between 0.0 and 1.0 indicating how far down the screen the text should be shown, as a percentage of the height, from the top. """
                },
                result='returns true if the position was successfully set, false otherwise.' ,
            ),
            url='textItemSetPosition',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemSetPriority',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['void'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextItem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='priority',
                                argument_type=FunctionType(
                                    names=['string'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function sets the priority for a text item.  Priority is the importance of sending updated text to the client. The system is implemented as 3 queues, with the high queue being emptied before the medium queue is processed, and with one update sent per server frame. Hence, if you set all your text items to medium priority it has the same effect as if you set them all to high or low.' ,
                arguments={
                    "theTextItem": """The text item you wish to set priority to. """,
                    "priority": """The priority you wish to set to the item, which can be high, medium, or low respective of their priority. """
                },
                result='' ,
            ),
            url='textItemSetPriority',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemSetScale',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['bool'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextitem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='scale',
                                argument_type=FunctionType(
                                    names=['float'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='This function allows the setting of the scale of a text item.' ,
                arguments={
                    "theTextitem": """The text item you wish to set the scale of. """,
                    "scale": """A floating point value indicating the scale of the text you wish to set to. 1.0 is around 12pt. """
                },
                result='returns true if the scale was successfully set, false otherwise.' ,
            ),
            url='textItemSetScale',
        )
        ],
        client=[
            
        ],
    ),
    CompoundFunctionData(
        server=[
            FunctionData(
            signature=FunctionSignature(
                name='textItemSetText',
                return_types=FunctionReturnTypes(
                    return_types=[
                        FunctionType(
                                    names=['void'],
                                    is_optional=False,
                                )
                    ],
                    variable_length=False,
                ),
                arguments=FunctionArgumentValues(
                    arguments=[
                        [
                            FunctionArgument(
                                name='theTextitem',
                                argument_type=FunctionType(
                                    names=['textitem'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ],
                        [
                            FunctionArgument(
                                name='text',
                                argument_type=FunctionType(
                                    names=['string'],
                                    is_optional=False,
                                ),
                                default_value=None,
                            )
                        ]
                    ],
                    variable_length=False,
                ),
                generic_types=[
                    
                ],
            ),
            docs=FunctionDoc(
                description='Overwrites a previously created text item with the specified text.' ,
                arguments={
                    "theTextitem": """An existing text item that was previously created with textCreateTextItem """,
                    "text": """The new text for the text item """
                },
                result='' ,
            ),
            url='textItemSetText',
        )
        ],
        client=[
            
        ],
    )
]
