# Autogenerated file. ANY CHANGES WILL BE OVERWRITTEN
from to_python.dump.functions.account_functions import DUMP_PARTIAL as DP_F_ACCOUNT_FUNCTIONS
from to_python.dump.functions.acl_functions import DUMP_PARTIAL as DP_F_ACL_FUNCTIONS
from to_python.dump.functions.admin_functions import DUMP_PARTIAL as DP_F_ADMIN_FUNCTIONS
from to_python.dump.functions.announcement_functions import DUMP_PARTIAL as DP_F_ANNOUNCEMENT_FUNCTIONS
from to_python.dump.functions.audio_functions import DUMP_PARTIAL as DP_F_AUDIO_FUNCTIONS
from to_python.dump.functions.blip_functions import DUMP_PARTIAL as DP_F_BLIP_FUNCTIONS
from to_python.dump.functions.browser_functions import DUMP_PARTIAL as DP_F_BROWSER_FUNCTIONS
from to_python.dump.functions.camera_functions import DUMP_PARTIAL as DP_F_CAMERA_FUNCTIONS
from to_python.dump.functions.clothes_and_body_functions import DUMP_PARTIAL as DP_F_CLOTHES_AND_BODY_FUNCTIONS
from to_python.dump.functions.collision_shape_functions import DUMP_PARTIAL as DP_F_COLLISION_SHAPE_FUNCTIONS
from to_python.dump.functions.cursor_functions import DUMP_PARTIAL as DP_F_CURSOR_FUNCTIONS
from to_python.dump.functions.drawing_functions import DUMP_PARTIAL as DP_F_DRAWING_FUNCTIONS
from to_python.dump.functions.effects_functions import DUMP_PARTIAL as DP_F_EFFECTS_FUNCTIONS
from to_python.dump.functions.element_functions import DUMP_PARTIAL as DP_F_ELEMENT_FUNCTIONS
from to_python.dump.functions.engine_functions import DUMP_PARTIAL as DP_F_ENGINE_FUNCTIONS
from to_python.dump.functions.event_functions import DUMP_PARTIAL as DP_F_EVENT_FUNCTIONS
from to_python.dump.functions.explosion_functions import DUMP_PARTIAL as DP_F_EXPLOSION_FUNCTIONS
from to_python.dump.functions.file_functions import DUMP_PARTIAL as DP_F_FILE_FUNCTIONS
from to_python.dump.functions.fire_functions import DUMP_PARTIAL as DP_F_FIRE_FUNCTIONS
from to_python.dump.functions.gui_functions import DUMP_PARTIAL as DP_F_GUI_FUNCTIONS
from to_python.dump.functions.input_functions import DUMP_PARTIAL as DP_F_INPUT_FUNCTIONS
from to_python.dump.functions.light_functions import DUMP_PARTIAL as DP_F_LIGHT_FUNCTIONS
from to_python.dump.functions.map_functions import DUMP_PARTIAL as DP_F_MAP_FUNCTIONS
from to_python.dump.functions.marker_functions import DUMP_PARTIAL as DP_F_MARKER_FUNCTIONS
from to_python.dump.functions.module_functions import DUMP_PARTIAL as DP_F_MODULE_FUNCTIONS
from to_python.dump.functions.object_functions import DUMP_PARTIAL as DP_F_OBJECT_FUNCTIONS
from to_python.dump.functions.output_functions import DUMP_PARTIAL as DP_F_OUTPUT_FUNCTIONS
from to_python.dump.functions.ped_functions import DUMP_PARTIAL as DP_F_PED_FUNCTIONS
from to_python.dump.functions.pickup_functions import DUMP_PARTIAL as DP_F_PICKUP_FUNCTIONS
from to_python.dump.functions.player_functions import DUMP_PARTIAL as DP_F_PLAYER_FUNCTIONS
from to_python.dump.functions.projectile_functions import DUMP_PARTIAL as DP_F_PROJECTILE_FUNCTIONS
from to_python.dump.functions.radar_area_functions import DUMP_PARTIAL as DP_F_RADAR_AREA_FUNCTIONS
from to_python.dump.functions.resource_functions import DUMP_PARTIAL as DP_F_RESOURCE_FUNCTIONS
from to_python.dump.functions.searchlight_functions import DUMP_PARTIAL as DP_F_SEARCHLIGHT_FUNCTIONS
from to_python.dump.functions.server_functions import DUMP_PARTIAL as DP_F_SERVER_FUNCTIONS
from to_python.dump.functions.settings_registry_functions import DUMP_PARTIAL as DP_F_SETTINGS_REGISTRY_FUNCTIONS
from to_python.dump.functions.sql_functions import DUMP_PARTIAL as DP_F_SQL_FUNCTIONS
from to_python.dump.functions.svg_functions import DUMP_PARTIAL as DP_F_SVG_FUNCTIONS
from to_python.dump.functions.team_functions import DUMP_PARTIAL as DP_F_TEAM_FUNCTIONS
from to_python.dump.functions.text_functions import DUMP_PARTIAL as DP_F_TEXT_FUNCTIONS
from to_python.dump.functions.utf8_library import DUMP_PARTIAL as DP_F_UTF8_LIBRARY
from to_python.dump.functions.utility_functions import DUMP_PARTIAL as DP_F_UTILITY_FUNCTIONS
from to_python.dump.functions.vehicle_functions import DUMP_PARTIAL as DP_F_VEHICLE_FUNCTIONS
from to_python.dump.functions.water_functions import DUMP_PARTIAL as DP_F_WATER_FUNCTIONS
from to_python.dump.functions.weapon_creation_functions import DUMP_PARTIAL as DP_F_WEAPON_CREATION_FUNCTIONS
from to_python.dump.functions.weapon_functions import DUMP_PARTIAL as DP_F_WEAPON_FUNCTIONS
from to_python.dump.functions.world_functions import DUMP_PARTIAL as DP_F_WORLD_FUNCTIONS
from to_python.dump.functions.xml_functions import DUMP_PARTIAL as DP_F_XML_FUNCTIONS

DUMP_FUNCTIONS = [
    *DP_F_ACCOUNT_FUNCTIONS,
    *DP_F_ACL_FUNCTIONS,
    *DP_F_ADMIN_FUNCTIONS,
    *DP_F_ANNOUNCEMENT_FUNCTIONS,
    *DP_F_AUDIO_FUNCTIONS,
    *DP_F_BLIP_FUNCTIONS,
    *DP_F_BROWSER_FUNCTIONS,
    *DP_F_CAMERA_FUNCTIONS,
    *DP_F_CLOTHES_AND_BODY_FUNCTIONS,
    *DP_F_COLLISION_SHAPE_FUNCTIONS,
    *DP_F_CURSOR_FUNCTIONS,
    *DP_F_DRAWING_FUNCTIONS,
    *DP_F_EFFECTS_FUNCTIONS,
    *DP_F_ELEMENT_FUNCTIONS,
    *DP_F_ENGINE_FUNCTIONS,
    *DP_F_EVENT_FUNCTIONS,
    *DP_F_EXPLOSION_FUNCTIONS,
    *DP_F_FILE_FUNCTIONS,
    *DP_F_FIRE_FUNCTIONS,
    *DP_F_GUI_FUNCTIONS,
    *DP_F_INPUT_FUNCTIONS,
    *DP_F_LIGHT_FUNCTIONS,
    *DP_F_MAP_FUNCTIONS,
    *DP_F_MARKER_FUNCTIONS,
    *DP_F_MODULE_FUNCTIONS,
    *DP_F_OBJECT_FUNCTIONS,
    *DP_F_OUTPUT_FUNCTIONS,
    *DP_F_PED_FUNCTIONS,
    *DP_F_PICKUP_FUNCTIONS,
    *DP_F_PLAYER_FUNCTIONS,
    *DP_F_PROJECTILE_FUNCTIONS,
    *DP_F_RADAR_AREA_FUNCTIONS,
    *DP_F_RESOURCE_FUNCTIONS,
    *DP_F_SEARCHLIGHT_FUNCTIONS,
    *DP_F_SERVER_FUNCTIONS,
    *DP_F_SETTINGS_REGISTRY_FUNCTIONS,
    *DP_F_SQL_FUNCTIONS,
    *DP_F_SVG_FUNCTIONS,
    *DP_F_TEAM_FUNCTIONS,
    *DP_F_TEXT_FUNCTIONS,
    *DP_F_UTF8_LIBRARY,
    *DP_F_UTILITY_FUNCTIONS,
    *DP_F_VEHICLE_FUNCTIONS,
    *DP_F_WATER_FUNCTIONS,
    *DP_F_WEAPON_CREATION_FUNCTIONS,
    *DP_F_WEAPON_FUNCTIONS,
    *DP_F_WORLD_FUNCTIONS,
    *DP_F_XML_FUNCTIONS
]


from to_python.dump.oops.account_functions import DUMP_PARTIAL as DP_O_ACCOUNT_FUNCTIONS
from to_python.dump.oops.acl_functions import DUMP_PARTIAL as DP_O_ACL_FUNCTIONS
from to_python.dump.oops.admin_functions import DUMP_PARTIAL as DP_O_ADMIN_FUNCTIONS
from to_python.dump.oops.announcement_functions import DUMP_PARTIAL as DP_O_ANNOUNCEMENT_FUNCTIONS
from to_python.dump.oops.audio_functions import DUMP_PARTIAL as DP_O_AUDIO_FUNCTIONS
from to_python.dump.oops.blip_functions import DUMP_PARTIAL as DP_O_BLIP_FUNCTIONS
from to_python.dump.oops.browser_functions import DUMP_PARTIAL as DP_O_BROWSER_FUNCTIONS
from to_python.dump.oops.camera_functions import DUMP_PARTIAL as DP_O_CAMERA_FUNCTIONS
from to_python.dump.oops.clothes_and_body_functions import DUMP_PARTIAL as DP_O_CLOTHES_AND_BODY_FUNCTIONS
from to_python.dump.oops.collision_shape_functions import DUMP_PARTIAL as DP_O_COLLISION_SHAPE_FUNCTIONS
from to_python.dump.oops.cursor_functions import DUMP_PARTIAL as DP_O_CURSOR_FUNCTIONS
from to_python.dump.oops.drawing_functions import DUMP_PARTIAL as DP_O_DRAWING_FUNCTIONS
from to_python.dump.oops.effects_functions import DUMP_PARTIAL as DP_O_EFFECTS_FUNCTIONS
from to_python.dump.oops.element_functions import DUMP_PARTIAL as DP_O_ELEMENT_FUNCTIONS
from to_python.dump.oops.engine_functions import DUMP_PARTIAL as DP_O_ENGINE_FUNCTIONS
from to_python.dump.oops.event_functions import DUMP_PARTIAL as DP_O_EVENT_FUNCTIONS
from to_python.dump.oops.explosion_functions import DUMP_PARTIAL as DP_O_EXPLOSION_FUNCTIONS
from to_python.dump.oops.file_functions import DUMP_PARTIAL as DP_O_FILE_FUNCTIONS
from to_python.dump.oops.fire_functions import DUMP_PARTIAL as DP_O_FIRE_FUNCTIONS
from to_python.dump.oops.gui_functions import DUMP_PARTIAL as DP_O_GUI_FUNCTIONS
from to_python.dump.oops.input_functions import DUMP_PARTIAL as DP_O_INPUT_FUNCTIONS
from to_python.dump.oops.light_functions import DUMP_PARTIAL as DP_O_LIGHT_FUNCTIONS
from to_python.dump.oops.map_functions import DUMP_PARTIAL as DP_O_MAP_FUNCTIONS
from to_python.dump.oops.marker_functions import DUMP_PARTIAL as DP_O_MARKER_FUNCTIONS
from to_python.dump.oops.module_functions import DUMP_PARTIAL as DP_O_MODULE_FUNCTIONS
from to_python.dump.oops.object_functions import DUMP_PARTIAL as DP_O_OBJECT_FUNCTIONS
from to_python.dump.oops.output_functions import DUMP_PARTIAL as DP_O_OUTPUT_FUNCTIONS
from to_python.dump.oops.ped_functions import DUMP_PARTIAL as DP_O_PED_FUNCTIONS
from to_python.dump.oops.pickup_functions import DUMP_PARTIAL as DP_O_PICKUP_FUNCTIONS
from to_python.dump.oops.player_functions import DUMP_PARTIAL as DP_O_PLAYER_FUNCTIONS
from to_python.dump.oops.projectile_functions import DUMP_PARTIAL as DP_O_PROJECTILE_FUNCTIONS
from to_python.dump.oops.radar_area_functions import DUMP_PARTIAL as DP_O_RADAR_AREA_FUNCTIONS
from to_python.dump.oops.resource_functions import DUMP_PARTIAL as DP_O_RESOURCE_FUNCTIONS
from to_python.dump.oops.searchlight_functions import DUMP_PARTIAL as DP_O_SEARCHLIGHT_FUNCTIONS
from to_python.dump.oops.server_functions import DUMP_PARTIAL as DP_O_SERVER_FUNCTIONS
from to_python.dump.oops.settings_registry_functions import DUMP_PARTIAL as DP_O_SETTINGS_REGISTRY_FUNCTIONS
from to_python.dump.oops.sql_functions import DUMP_PARTIAL as DP_O_SQL_FUNCTIONS
from to_python.dump.oops.svg_functions import DUMP_PARTIAL as DP_O_SVG_FUNCTIONS
from to_python.dump.oops.team_functions import DUMP_PARTIAL as DP_O_TEAM_FUNCTIONS
from to_python.dump.oops.text_functions import DUMP_PARTIAL as DP_O_TEXT_FUNCTIONS
from to_python.dump.oops.utf8_library import DUMP_PARTIAL as DP_O_UTF8_LIBRARY
from to_python.dump.oops.utility_functions import DUMP_PARTIAL as DP_O_UTILITY_FUNCTIONS
from to_python.dump.oops.vehicle_functions import DUMP_PARTIAL as DP_O_VEHICLE_FUNCTIONS
from to_python.dump.oops.water_functions import DUMP_PARTIAL as DP_O_WATER_FUNCTIONS
from to_python.dump.oops.weapon_creation_functions import DUMP_PARTIAL as DP_O_WEAPON_CREATION_FUNCTIONS
from to_python.dump.oops.weapon_functions import DUMP_PARTIAL as DP_O_WEAPON_FUNCTIONS
from to_python.dump.oops.world_functions import DUMP_PARTIAL as DP_O_WORLD_FUNCTIONS
from to_python.dump.oops.xml_functions import DUMP_PARTIAL as DP_O_XML_FUNCTIONS

DUMP_OOPS = [
    *DP_O_ACCOUNT_FUNCTIONS,
    *DP_O_ACL_FUNCTIONS,
    *DP_O_ADMIN_FUNCTIONS,
    *DP_O_ANNOUNCEMENT_FUNCTIONS,
    *DP_O_AUDIO_FUNCTIONS,
    *DP_O_BLIP_FUNCTIONS,
    *DP_O_BROWSER_FUNCTIONS,
    *DP_O_CAMERA_FUNCTIONS,
    *DP_O_CLOTHES_AND_BODY_FUNCTIONS,
    *DP_O_COLLISION_SHAPE_FUNCTIONS,
    *DP_O_CURSOR_FUNCTIONS,
    *DP_O_DRAWING_FUNCTIONS,
    *DP_O_EFFECTS_FUNCTIONS,
    *DP_O_ELEMENT_FUNCTIONS,
    *DP_O_ENGINE_FUNCTIONS,
    *DP_O_EVENT_FUNCTIONS,
    *DP_O_EXPLOSION_FUNCTIONS,
    *DP_O_FILE_FUNCTIONS,
    *DP_O_FIRE_FUNCTIONS,
    *DP_O_GUI_FUNCTIONS,
    *DP_O_INPUT_FUNCTIONS,
    *DP_O_LIGHT_FUNCTIONS,
    *DP_O_MAP_FUNCTIONS,
    *DP_O_MARKER_FUNCTIONS,
    *DP_O_MODULE_FUNCTIONS,
    *DP_O_OBJECT_FUNCTIONS,
    *DP_O_OUTPUT_FUNCTIONS,
    *DP_O_PED_FUNCTIONS,
    *DP_O_PICKUP_FUNCTIONS,
    *DP_O_PLAYER_FUNCTIONS,
    *DP_O_PROJECTILE_FUNCTIONS,
    *DP_O_RADAR_AREA_FUNCTIONS,
    *DP_O_RESOURCE_FUNCTIONS,
    *DP_O_SEARCHLIGHT_FUNCTIONS,
    *DP_O_SERVER_FUNCTIONS,
    *DP_O_SETTINGS_REGISTRY_FUNCTIONS,
    *DP_O_SQL_FUNCTIONS,
    *DP_O_SVG_FUNCTIONS,
    *DP_O_TEAM_FUNCTIONS,
    *DP_O_TEXT_FUNCTIONS,
    *DP_O_UTF8_LIBRARY,
    *DP_O_UTILITY_FUNCTIONS,
    *DP_O_VEHICLE_FUNCTIONS,
    *DP_O_WATER_FUNCTIONS,
    *DP_O_WEAPON_CREATION_FUNCTIONS,
    *DP_O_WEAPON_FUNCTIONS,
    *DP_O_WORLD_FUNCTIONS,
    *DP_O_XML_FUNCTIONS
]


from to_python.dump.events.account_events import DUMP_PARTIAL as DP_E_ACCOUNT_EVENTS
from to_python.dump.events.browser_events import DUMP_PARTIAL as DP_E_BROWSER_EVENTS
from to_python.dump.events.client_events import DUMP_PARTIAL as DP_E_CLIENT_EVENTS
from to_python.dump.events.colshape_events import DUMP_PARTIAL as DP_E_COLSHAPE_EVENTS
from to_python.dump.events.element_events import DUMP_PARTIAL as DP_E_ELEMENT_EVENTS
from to_python.dump.events.input_events import DUMP_PARTIAL as DP_E_INPUT_EVENTS
from to_python.dump.events.marker_events import DUMP_PARTIAL as DP_E_MARKER_EVENTS
from to_python.dump.events.object_events import DUMP_PARTIAL as DP_E_OBJECT_EVENTS
from to_python.dump.events.other_events import DUMP_PARTIAL as DP_E_OTHER_EVENTS
from to_python.dump.events.ped_events import DUMP_PARTIAL as DP_E_PED_EVENTS
from to_python.dump.events.pickup_events import DUMP_PARTIAL as DP_E_PICKUP_EVENTS
from to_python.dump.events.player_events import DUMP_PARTIAL as DP_E_PLAYER_EVENTS
from to_python.dump.events.projectile_events import DUMP_PARTIAL as DP_E_PROJECTILE_EVENTS
from to_python.dump.events.resource_events import DUMP_PARTIAL as DP_E_RESOURCE_EVENTS
from to_python.dump.events.server_events import DUMP_PARTIAL as DP_E_SERVER_EVENTS
from to_python.dump.events.sound_events import DUMP_PARTIAL as DP_E_SOUND_EVENTS
from to_python.dump.events.vehicle_events import DUMP_PARTIAL as DP_E_VEHICLE_EVENTS
from to_python.dump.events.weapon_creation_events import DUMP_PARTIAL as DP_E_WEAPON_CREATION_EVENTS
from to_python.dump.events.weapon_events import DUMP_PARTIAL as DP_E_WEAPON_EVENTS

DUMP_EVENTS = [
    *DP_E_ACCOUNT_EVENTS,
    *DP_E_BROWSER_EVENTS,
    *DP_E_CLIENT_EVENTS,
    *DP_E_COLSHAPE_EVENTS,
    *DP_E_ELEMENT_EVENTS,
    *DP_E_INPUT_EVENTS,
    *DP_E_MARKER_EVENTS,
    *DP_E_OBJECT_EVENTS,
    *DP_E_OTHER_EVENTS,
    *DP_E_PED_EVENTS,
    *DP_E_PICKUP_EVENTS,
    *DP_E_PLAYER_EVENTS,
    *DP_E_PROJECTILE_EVENTS,
    *DP_E_RESOURCE_EVENTS,
    *DP_E_SERVER_EVENTS,
    *DP_E_SOUND_EVENTS,
    *DP_E_VEHICLE_EVENTS,
    *DP_E_WEAPON_CREATION_EVENTS,
    *DP_E_WEAPON_EVENTS
]
